---
sidebar_position: 1
---

# 准备工作

## 区别实例对象与函数对象

- 实例对象：`new` 一个构造函数产生的对象，称为实例对象，简称为对象；
- 函数对象：将函数作为对象使用时，简称为函数对象。

```js
// Fn 是函数
function Fn() {}

// Fn 只有 new 的时候才可以称为构造函数
// fn 称为实例对象（简称为对象）
const fn = new Fn()

// Fn 作为对象使用时，称为函数对象
console.log(Fn.prototype)		
Fn.bind({})

// $ 作为函数使用
$('#test')
// $ 作为函数对象使用
$.get('/test')
```

## 两种类型的回调函数

### 同步回调

同步回调：立即执行，完全执行完了才结束，不会放入回调队列中。

如：数组遍历相关的回调、Promise 的 executor 函数等。

```js
const arr = [1, 3, 5]
arr.forEach(item => {   // 同步回调函数，不会放入回调队列，而是立即执行
  console.log(item)
})
console.log('forEach()之后')

// 1
// 3
// 5
// forEach()之后
```

### 异步回调

异步回调：不会立即执行，而是放入回调队列中，将来执行。

如：定时器回调、ajax 回调、Promise 成功或失败的回调等。

```js title="定时器回调"
setTimeout(() => {    // 异步回调函数，会放入回调队列中，将来执行（所有同步任务执行完后才可能执行）
  console.log('timeout callback()')
}, 0)
console.log('setTimeout()之后')

// setTimeout()之后
// timeout callback()
```

```js title="Promise 成功或失败的回调"
new Promise((resolve, reject) => {
  resolve(1)
}).then(value => {
  console.log('value', value)
}, reason => {
  console.log('reason', reason)
})
console.log('----')

// ----
// value 1
```

### 总结

JS 引擎先把初始化的同步代码（同步任务）都执行完成后，再执行回调队列中的代码（异步任务）。

## JS 中的异常（error）处理

### 错误的类型

`Error`：所有错误的父类型。

```js title="ReferenceError：引用的变量不存在"
console.log(a)  // ReferenceError: a is not defined
```

```js title="TypeError：数据类型不正确"
let b
console.log(b.xxx)  // TypeError: Cannot read property 'xxx' of undefined

let c = {}
c.xxx()   // TypeError: c.xxx is not a function
```

```js title="RangeError：数据值不在其所允许的范围内"
function fn() {
  fn()
}
fn()    // RangeError: Maximum call stack size exceeded
```

```js title="SyntaxError：语法错误"
const c = """"    // SyntaxError: Unexpected string
```

### 错误处理（捕获错误与抛出错误）

如果不对错误进行捕获，那么后面的代码就无法执行。

```js
function something() {
  if (Date.now() % 2 === 1) {
    console.log('当前时间为奇数，可以执行任务')
  } else {
    // 抛出错误
    throw new Error('当前时间为偶数，无法执行任务')
  }
}

// 捕获错误
try {
  something()
} catch (error) {
  alert(error.message)
}

console.log('出错之后')
```

以上代码，因为错误被捕获处理了，所以后面的代码可以运行下去，打印出 `"出错之后"`。

### Error 对象的结构

```js
try {
  let d
  console.log(d.xxx)
} catch (error) {
  // error 是一个对象，其中含有 message、stack 等属性
  console.log(error.message)   // 错误相关信息
  console.log(error.stack)     // 函数调用栈记录信息
}
```


